/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package os;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jpl = new javax.swing.JPanel();
        jlb1 = new javax.swing.JLabel();
        jlb2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jlb3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlb_name = new javax.swing.JLabel();
        jlb_pro = new javax.swing.JLabel();
        jlb_arrive = new javax.swing.JLabel();
        jlb_serve = new javax.swing.JLabel();
        jtf_name = new javax.swing.JTextField();
        jtf_serve = new javax.swing.JTextField();
        jtf_pro = new javax.swing.JTextField();
        jtf_arrive = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpl.setBackground(new java.awt.Color(204, 204, 255));

        jlb1.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jlb1.setText("调度算法选择");

        jlb2.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jlb2.setText("读取进程");

        jRadioButton1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jRadioButton1.setText("先到先服务算法");

        jRadioButton2.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jRadioButton2.setText("短作业优先算法");

        jRadioButton3.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jRadioButton3.setText("时间片轮转算法");

        jRadioButton4.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jRadioButton4.setText("基于静态优先级算法");

        jRadioButton5.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jRadioButton5.setText("基于高响应比优先的动态优先级算法");

        jRadioButton6.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jRadioButton6.setText("读取文件");

        jRadioButton7.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jRadioButton7.setText("手动输入");

        jlb3.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jlb3.setText("输入进程");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "进程名", "到达时间", "服务时间", "优先级"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jlb_name.setBackground(new java.awt.Color(204, 204, 255));
        jlb_name.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jlb_name.setText("进程名：");

        jlb_pro.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jlb_pro.setText("优先级：");

        jlb_arrive.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jlb_arrive.setText("到达时间：");

        jlb_serve.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jlb_serve.setText("服务时间：");

        jtf_name.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N

        jtf_serve.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N

        jtf_pro.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N

        jtf_arrive.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jButton1.setText("新建");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jButton2.setText("修改");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jButton3.setText("删除");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jButton4.setText("确认");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 204, 204));
        jButton5.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jButton5.setText("开始");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 204, 204));
        jButton6.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        jButton6.setText("清空");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel1.setText("结果展示");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jplLayout = new javax.swing.GroupLayout(jpl);
        jpl.setLayout(jplLayout);
        jplLayout.setHorizontalGroup(
            jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlb1)
                    .addComponent(jlb2)
                    .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlb3))
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlb_arrive)
                                .addComponent(jlb_name)
                                .addComponent(jlb_serve))
                            .addComponent(jlb_pro))
                        .addGap(28, 28, 28)
                        .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_arrive, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_serve, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jplLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jplLayout.createSequentialGroup()
                                .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton6)
                                    .addComponent(jRadioButton1))
                                .addGap(32, 32, 32)
                                .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton7)
                                    .addGroup(jplLayout.createSequentialGroup()
                                        .addComponent(jRadioButton2)
                                        .addGap(32, 32, 32)
                                        .addComponent(jRadioButton3)
                                        .addGap(34, 34, 34)
                                        .addComponent(jRadioButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                        .addComponent(jRadioButton5))))
                            .addGroup(jplLayout.createSequentialGroup()
                                .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(32, 32, 32))
        );
        jplLayout.setVerticalGroup(
            jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlb3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jplLayout.createSequentialGroup()
                        .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_arrive, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_arrive, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_serve, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_serve, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlb_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtf_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jplLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1106, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        Vector V_Add=new Vector();//构造一个空向量V_Add
        //获取文本字段中的内容
        V_Add.add(jtf_name.getText());
        V_Add.add(jtf_arrive.getText());
        V_Add.add(jtf_serve.getText());
        V_Add.add(jtf_pro.getText());
        dtm.addRow(V_Add);//添加完信息后表格自动添加一行。
 //添加完后文本字段中内容清空
        jtf_name.setText(null);
        jtf_arrive.setText(null);
        jtf_serve.setText(null);
        jtf_pro.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //找到鼠标选中的表格中的行和列，显示在文本中，进行修改，最后清空文本字段中信息。
       DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
	int row = jTable1.getSelectedRow();
	// dtm.setValueAt(jtf_name.getText(), row, 0);
	// dtm.setValueAt(jtf_arrive.getText(), row, 1);
	// dtm.setValueAt(jtf_serve.getText(), row, 2);
	// dtm.setValueAt(jtf_pro.getText(), row, 3);
	jtf_name.setText(jTable1.getValueAt(row, 0).toString());
	jtf_arrive.setText(jTable1.getValueAt(row, 1).toString());
	jtf_serve.setText(jTable1.getValueAt(row, 2).toString());
	jtf_pro.setText(jTable1.getValueAt(row, 3).toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        int row=jTable1.getSelectedRow();
        dtm.removeRow(row);
        jtf_name.setText(null);
        jtf_arrive.setText(null);
        jtf_serve.setText(null);
        jtf_pro.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //清空
        jTextArea1.setText(null);
    }//GEN-LAST:event_jButton6ActionPerformed
    Create create = new Create();
    Node head = null;
    Algorithm al = new Algorithm();
    String name;
    int arrivetime;
    int servetime;
    int priority;

	public static Node readFileContent(String fileName) {
		Node node = new Node();
		File file = new File(fileName);
		BufferedReader reader = null;
		int num = 0;
		List<String> sbf = new ArrayList<String>();
		try {
			reader = new BufferedReader(new FileReader(file));
			String tempStr;
			while ((tempStr = reader.readLine()) != null) {
				if (num == 0) {
				} else {
					sbf.add(tempStr);
				}
				num++;
			}
			Node child = null;
			Node parent = null;
			for (int i = (sbf.size() - 1); i >= 0; i--) {
				parent = new Node();
				String[] arr = sbf.get(i).split("        ");
				String name = arr[0];
				String s1 = arr[1].replace(" ", "");
				int arrivaltime = Integer.valueOf(s1);
				String s2 = arr[2].replace(" ", "");
				int runtime = Integer.valueOf(s2);
				String s3 = arr[3].replace(" ", "");
				int priority = Integer.valueOf(s3);
				parent.setName(name);
				parent.setArrivaltime(arrivaltime);
				parent.setRuntime(runtime);
				parent.setPriority(priority);
				parent.setNextnode(child);
				child = new Node();
				child = parent;
			}

			reader.close();
			return child;
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			if (reader != null) {
				try {
					reader.close();
				} catch (IOException e1) {
					e1.printStackTrace();
				}
			}
		}
		return node;
	}

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //确认
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
		int row = jTable1.getSelectedRow();
		dtm.setValueAt(jtf_name.getText(), row, 0);
		dtm.setValueAt(jtf_arrive.getText(), row, 1);
		dtm.setValueAt(jtf_serve.getText(), row, 2);
		dtm.setValueAt(jtf_pro.getText(), row, 3);
		jtf_name.setText(null);
		jtf_arrive.setText(null);
		jtf_serve.setText(null);
		jtf_pro.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        // 开始
		if (jRadioButton1.isSelected()) {// 先到先服务
			if (jRadioButton6.isSelected()) {// 读取文件
				int result = 0;
				String path = null;
				JFileChooser fileChooser = new JFileChooser();
				FileSystemView fsv = FileSystemView.getFileSystemView(); // 注意了，这里重要的一句
				fileChooser.setCurrentDirectory(fsv.getHomeDirectory());
				fileChooser.setDialogTitle("请选择要读取的文件...");
				fileChooser.setApproveButtonText("确定");
				fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
				result = fileChooser.showOpenDialog(jpl);
				if (JFileChooser.APPROVE_OPTION == result) {
					path = fileChooser.getSelectedFile().getPath();
					Node tmp = readFileContent(path);
					name = al.FCFS(tmp);
					jTextArea1.setText(name.toString());
				}
			}
			if (jRadioButton7.isSelected()) {// 读取输入
				DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
				int rowCount = dtm.getRowCount();
				Node child = null;
				Node parent = null;
				for (int i = (rowCount - 1); i >= 0; i--)// 表格中的行数
				{
					parent = new Node();
					parent.setName(jTable1.getValueAt(i, 0).toString());
					parent.setArrivaltime(Integer.valueOf(jTable1.getValueAt(i, 1).toString()));
					parent.setRuntime(Integer.valueOf(jTable1.getValueAt(i, 2).toString()));
					parent.setPriority(Integer.valueOf(jTable1.getValueAt(i, 3).toString()));
					parent.setNextnode(child);
					child = new Node();
					child = parent;
				}
				name = al.FCFS(child);
				jTextArea1.setText(name.toString());
			}
		}
		if (jRadioButton2.isSelected()) {// 短作业优先
			if (jRadioButton6.isSelected()) {// 读取文件
				int result = 0;
				String path = null;
				JFileChooser fileChooser = new JFileChooser();
				FileSystemView fsv = FileSystemView.getFileSystemView(); // 注意了，这里重要的一句
				fileChooser.setCurrentDirectory(fsv.getHomeDirectory());
				fileChooser.setDialogTitle("请选择要读取的文件...");
				fileChooser.setApproveButtonText("确定");
				fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
				result = fileChooser.showOpenDialog(jpl);
				if (JFileChooser.APPROVE_OPTION == result) {
					path = fileChooser.getSelectedFile().getPath();
					Node tmp = readFileContent(path);
					name = al.SPN(tmp);
					jTextArea1.setText(name.toString());
				}
			}
			if (jRadioButton7.isSelected()) {// 读取输入
				DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
				int rowCount = dtm.getRowCount();
				Node child = null;
				Node parent = null;
				for (int i = (rowCount - 1); i >= 0; i--)// 表格中的行数
				{
					parent = new Node();
					parent.setName(jTable1.getValueAt(i, 0).toString());
					parent.setArrivaltime(Integer.valueOf(jTable1.getValueAt(i, 1).toString()));
					parent.setRuntime(Integer.valueOf(jTable1.getValueAt(i, 2).toString()));
					parent.setPriority(Integer.valueOf(jTable1.getValueAt(i, 3).toString()));
					parent.setNextnode(child);
					child = new Node();
					child = parent;
				}
				name = al.SPN(child);
				jTextArea1.setText(name.toString());
			}
		}
		if (jRadioButton3.isSelected())

		{// 时间片轮转
			if (jRadioButton6.isSelected()) {// 读取文件
				int result = 0;
				String path = null;
				JFileChooser fileChooser = new JFileChooser();
				FileSystemView fsv = FileSystemView.getFileSystemView(); // 注意了，这里重要的一句
				fileChooser.setCurrentDirectory(fsv.getHomeDirectory());
				fileChooser.setDialogTitle("请选择要读取的文件...");
				fileChooser.setApproveButtonText("确定");
				fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
				result = fileChooser.showOpenDialog(jpl);
				if (JFileChooser.APPROVE_OPTION == result) {
					path = fileChooser.getSelectedFile().getPath();
					Node tmp = readFileContent(path);
					name = al.RR(tmp, 1);
					jTextArea1.setText(name.toString());
				}
			}
			if (jRadioButton7.isSelected()) {// 读取输入
				DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
				int rowCount = dtm.getRowCount();
				Node child = null;
				Node parent = null;
				for (int i = (rowCount - 1); i >= 0; i--)// 表格中的行数
				{
					parent = new Node();
					parent.setName(jTable1.getValueAt(i, 0).toString());
					parent.setArrivaltime(Integer.valueOf(jTable1.getValueAt(i, 1).toString()));
					parent.setRuntime(Integer.valueOf(jTable1.getValueAt(i, 2).toString()));
					parent.setPriority(Integer.valueOf(jTable1.getValueAt(i, 3).toString()));
					parent.setNextnode(child);
					child = new Node();
					child = parent;
				}
				name = al.RR(child, 1);
				jTextArea1.setText(name.toString());
			}
		}
		if (jRadioButton4.isSelected()) {// 静态优先级
			if (jRadioButton6.isSelected()) {// 读取文件
				int result = 0;
				String path = null;
				JFileChooser fileChooser = new JFileChooser();
				FileSystemView fsv = FileSystemView.getFileSystemView(); // 注意了，这里重要的一句
				fileChooser.setCurrentDirectory(fsv.getHomeDirectory());
				fileChooser.setDialogTitle("请选择要读取的文件...");
				fileChooser.setApproveButtonText("确定");
				fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
				result = fileChooser.showOpenDialog(jpl);
				if (JFileChooser.APPROVE_OPTION == result) {
					path = fileChooser.getSelectedFile().getPath();
					Node tmp = readFileContent(path);
					name = al.SPA(tmp);
					jTextArea1.setText(name.toString());
				}
			}
			if (jRadioButton7.isSelected()) {// 读取输入
				DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
				int rowCount = dtm.getRowCount();
				Node child = null;
				Node parent = null;
				for (int i = (rowCount - 1); i >= 0; i--)// 表格中的行数
				{
					parent = new Node();
					parent.setName(jTable1.getValueAt(i, 0).toString());
					parent.setArrivaltime(Integer.valueOf(jTable1.getValueAt(i, 1).toString()));
					parent.setRuntime(Integer.valueOf(jTable1.getValueAt(i, 2).toString()));
					parent.setPriority(Integer.valueOf(jTable1.getValueAt(i, 3).toString()));
					parent.setNextnode(child);
					child = new Node();
					child = parent;
				}
				name = al.SPA(child);
				jTextArea1.setText(name.toString());
			}
		}
		if (jRadioButton5.isSelected()) {// 高响应比优先
			if (jRadioButton6.isSelected()) {// 读取文件
				int result = 0;
				String path = null;
				JFileChooser fileChooser = new JFileChooser();
				FileSystemView fsv = FileSystemView.getFileSystemView(); // 注意了，这里重要的一句
				fileChooser.setCurrentDirectory(fsv.getHomeDirectory());
				fileChooser.setDialogTitle("请选择要读取的文件...");
				fileChooser.setApproveButtonText("确定");
				fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
				result = fileChooser.showOpenDialog(jpl);
				if (JFileChooser.APPROVE_OPTION == result) {
					path = fileChooser.getSelectedFile().getPath();
					Node tmp = readFileContent(path);
					name = al.HRRN(tmp);
					jTextArea1.setText(name.toString());
				}
			}
			if (jRadioButton7.isSelected()) {// 读取输入
				DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
				int rowCount = dtm.getRowCount();
				Node child = null;
				Node parent = null;
				for (int i = (rowCount - 1); i >= 0; i--)// 表格中的行数
				{
					parent = new Node();
					parent.setName(jTable1.getValueAt(i, 0).toString());
					parent.setArrivaltime(Integer.valueOf(jTable1.getValueAt(i, 1).toString()));
					parent.setRuntime(Integer.valueOf(jTable1.getValueAt(i, 2).toString()));
					parent.setPriority(Integer.valueOf(jTable1.getValueAt(i, 3).toString()));
					parent.setNextnode(child);
					child = new Node();
					child = parent;
				}
				name = al.HRRN(child);
				jTextArea1.setText(name.toString());
			}
		}
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Frame().setVisible(true);
			}
		});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlb1;
    private javax.swing.JLabel jlb2;
    private javax.swing.JLabel jlb3;
    private javax.swing.JLabel jlb_arrive;
    private javax.swing.JLabel jlb_name;
    private javax.swing.JLabel jlb_pro;
    private javax.swing.JLabel jlb_serve;
    private javax.swing.JPanel jpl;
    private javax.swing.JTextField jtf_arrive;
    private javax.swing.JTextField jtf_name;
    private javax.swing.JTextField jtf_pro;
    private javax.swing.JTextField jtf_serve;
    // End of variables declaration//GEN-END:variables
}
